#!/bin/sh
#
# quick script to automate incrementing
# custom CONFIG_LOCALVERSION value in kernel
# .config file
KERNEL_VER=4.19.143
KERNEL_DIR="$HOME/csce499/linux-$KERNEL_VER"
KERNEL_CFG=.config
LOCAL_VERSION_KEY="CONFIG_LOCALVERSION"
LOCAL_VERSION_REGEX='^(-DinterR-Devel-)([0-9]+)$'
# should be ${BASH_REMATCH[1]} of LOCAL_VERSION_REGEX
# basically should match the regex above.
LOCAL_VERSION_INIT_NUMBER=1
LOCAL_VERSION_INIT_SUBSTRING="-DinterR-Devel-$LOCAL_VERSION_INIT_NUMBER"

CURRENT_CONFIG_LOCALVERSION=`grep -w $LOCAL_VERSION_KEY "$KERNEL_DIR/$KERNEL_CFG"`
CURRENT_CONFIG_LOCALVERSION_VALUE=`echo $CURRENT_CONFIG_LOCALVERSION | cut -d= -f2 | sed -e 's/\"//g'` 

if [[ $CURRENT_CONFIG_LOCALVERSION_VALUE =~ $LOCAL_VERSION_REGEX ]]; then
  VERSION_NUMBER=${BASH_REMATCH[2]}
  NEXT_VERSION_NUMBER=$(($VERSION_NUMBER+1))
  VERSION_SUBSTRING=${BASH_REMATCH[1]}
  TARGET_CONFIG_LOCALVERSION="$LOCAL_VERSION_KEY=\"$VERSION_SUBSTRING$NEXT_VERSION_NUMBER\""
else
  VERSION_NUMBER=$LOCAL_VERSION_INIT_NUMBER
  TARGET_CONFIG_LOCALVERSION="$LOCAL_VERSION_KEY=\"$LOCAL_VERSION_INIT_SUBSTRING\""
fi

PREVIOUS_VERSION=$(($VERSION_NUMBER-1))

echo "====> Incrementing CONFIG_LOCALVERSION: $KERNEL_VER"
echo "old:  $CURRENT_CONFIG_LOCALVERSION"
echo "new:  $TARGET_CONFIG_LOCALVERSION"
rm -f "$KERNEL_DIR/$KERNEL_CFG.orig${PREVIOUS_VERSION}"
perl -pi.orig${VERSION_NUMBER} -e "s/$CURRENT_CONFIG_LOCALVERSION/$TARGET_CONFIG_LOCALVERSION/" "$KERNEL_DIR/$KERNEL_CFG"
