#!/bin/sh
#
# quick script to automate incrementing
# custom CONFIG_LOCALVERSION value in kernel
# .config file

source `pwd`/dinterbuild.env 2>/dev/null || exit 1

if [[ $CURRENT_CONFIG_LOCALVERSION_VALUE =~ $LOCAL_VERSION_REGEX ]]; then
  VERSION_NUMBER=${BASH_REMATCH[2]}
  NEXT_VERSION_NUMBER=$(($VERSION_NUMBER+1))
  VERSION_SUBSTRING=${BASH_REMATCH[1]}
  TARGET_CONFIG_LOCALVERSION="$LOCAL_VERSION_KEY=\"$VERSION_SUBSTRING$NEXT_VERSION_NUMBER\""
else
  VERSION_NUMBER=$LOCAL_VERSION_INIT_NUMBER
  TARGET_CONFIG_LOCALVERSION="$LOCAL_VERSION_KEY=\"$LOCAL_VERSION_INIT_SUBSTRING\""
fi

PREVIOUS_VERSION=$(($VERSION_NUMBER-1))

if [ -e $KERNEL_DIR/$KERNEL_CFG ];then
  echo "====> Incrementing CONFIG_LOCALVERSION: $KERNEL_VER"
  echo "old:  $CURRENT_CONFIG_LOCALVERSION"
  echo "new:  $TARGET_CONFIG_LOCALVERSION"
  rm -f "$KERNEL_DIR/$KERNEL_CFG.orig${PREVIOUS_VERSION}"
  perl -pi.orig${VERSION_NUMBER} -e "s/$CURRENT_CONFIG_LOCALVERSION/$TARGET_CONFIG_LOCALVERSION/" "$KERNEL_DIR/$KERNEL_CFG"
else
  exit 1
fi
